### ISSUE TITLE
compile error : solved

### ISSUE THREAD

**Issue by tissatussa** [macsmol/magog#10]
while compiling Magog v1.0 i got this error :

`go.mod:3: invalid go version '1.21.5': must match format 1.23`

so i changed it into "go 1.22" and compilation went well.
i found this solution by reading https://discourse.gohugo.io/t/github-pages-errors-parsing-go-mod-invalid-go-version/48513/4

Note: i didn't try "go 1.21" because it seems to me v1.21.5 is higher then v1.21 .. the v1.21.5 exists, but required is "format 1.23", with only one dot.

[ i'm on Xubuntu 22.04 ]

**Comment by macsmol** [comment]
1. Whats your version of go? Type
`go version`
2. Does it compile when you change it to "1.21" ?

**Comment by macsmol** [comment]
> Note: i didn't try "go 1.21" because it seems to me v1.21.5 is higher then v1.21 .. the v1.21.5 exists, but required is "format 1.23", with only one dot.

You don't have to worry about that. Go versioning seems to be following _semver_ convention. This means that increase of version after second dot should only contain bugfixes and not any compatibility-breaking changes. So you can safely use lower version.
AFAIK in practice it means that if you leave that part of version empty the build system is free to choose the latest (the best/most bugfree) version. So you type "1.21" and the system will pick "1.21.0" or "1.21.4" or "1.21.11" - whatever it has available.
If you could only confirm to me that 1.21 compiles without problems on your machine. It does on mine.

**Comment by tissatussa** [comment]
> confirm to me that 1.21 compiles without problems on your machine

yes it does :

```
~/Compiled/magog-1.0$ gvm use go1.21
Now using version go1.21.0

~/Compiled/magog-1.0$ go version
go version go1.21.0 linux/amd64

~/Compiled/magog-1.0$ go build .
~/Compiled/magog-1.0$ 
```

**Comment by macsmol** [comment]
I was considering to change version in go.mod to 1.21 but my research on the net shows that some people run into the opposite problem in their projects. I'm new to Go so IDK. For now I'll leave it as it is. If more people run into similar problem I'll just add troubleshooting to readme.

**Comment by tissatussa** [comment]
> ..Go versioning seems to be following semver convention..

i understand, but it seems `go.mod` needs the n.mm format, not n.mm.xx .. i had no problem compiling, i only had to adjust the `go.mod` file a little .. i'm new to Go also.
